name: PyLint
on: [ workflow_dispatch ]

defaults:
  run:
    shell: bash

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install pylint
        shell: bash
        run: pip3 install pylint

      - name: verify pylint installation
        shell: bash
        run: python3 -m pip list | grep pylint

      - name: Run pylint
        run: python3 -m pylint main.py
        shell: bash
